# Generated by Django 4.2.9 on 2025-05-16 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repairs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('mechanical', 'механический'), ('electrical', 'электрический'), ('technological', 'технологический')], max_length=20)),
                ('location', models.CharField(choices=[('ПНС', 'ПНС'), ('ТВС', 'ТВС'), ('ШХ', 'ШХ')], max_length=10)),
                ('last_ppr_date', models.DateField()),
                ('hours_at_deviation', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('shift_leader', models.CharField(max_length=120)),
                ('mechanic', models.CharField(max_length=120)),
                ('electrician', models.CharField(max_length=120)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dredger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviations', to='repairs.dredger')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
