# Generated by Django 4.2.9 on 2025-05-16 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DredgerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('norm_hours', models.PositiveIntegerField(help_text='Допустимая наработка, ч')),
                ('drawing_file', models.FileField(blank=True, upload_to='drawings/')),
            ],
        ),
        migrations.CreateModel(
            name='DredgerTypePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dredger_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refdata.dredgertype')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refdata.sparepart')),
            ],
            options={
                'unique_together': {('dredger_type', 'part')},
            },
        ),
    ]
